  #:for HISTORY_FLAG in HISTORY_FLAGS
  #:mute
  #:if HISTORY_FLAG
  #:  set HISTORY_SUFFIX = '_hist'
  #:  set HISTORY_INTENT = 'integer(DEFAULT_INT), intent(inout) :: history(:)'
  #:  set HISTORY_ARG = ', history'
  #:else
  #:  set HISTORY_SUFFIX = ''
  #:  set HISTORY_INTENT = ''
  #:  set HISTORY_ARG = ''
  #:endif
  #:endmute
  #:for KIND_SUFFIX, ARRAY_TYPE in IR_KINDS_TYPES
  subroutine swap_${KIND_SUFFIX}$${HISTORY_SUFFIX}$(arr, i, j${HISTORY_ARG}$)
    implicit none
    ${ARRAY_TYPE}$, intent(inout) :: arr(:)
    ${HISTORY_INTENT}$
    integer, intent(in) :: i, j
    ${ARRAY_TYPE}$ :: temp
    #{if HISTORY_FLAG}#integer(DEFAULT_INT) :: temp_hist#{endif}#
    temp = arr(i)
    arr(i) = arr(j)
    arr(j) = temp
    #:if HISTORY_FLAG
    temp_hist = history(i)
    history(i) = history(j)
    history(j) = temp_hist
    #:endif
  end subroutine swap_${KIND_SUFFIX}$${HISTORY_SUFFIX}$
  #:endfor
  #:endfor
