#:mute
#! number of bits of integer type
#:set INTEGER_BITS = [8, 16, 32, 64]
#!:set INTEGER_BITS = [32]

#! integer kinds
#:set INTEGER_KINDS = ["int{}".format(bits) for bits in INTEGER_BITS]

#! integer types
#:set INTEGER_TYPES = ["integer({})".format(kind) for kind in INTEGER_KINDS]

#! number of bits of real type
#:set REAL_BITS = [32, 64, 128]

#! real kinds
#:set REAL_KINDS = ["real{}".format(bits) for bits in REAL_BITS]

#! real types
#:set REAL_TYPES = ["real({})".format(kind) for kind in REAL_KINDS]

#! integer and real types
#:set IR_TYPES = INTEGER_TYPES + REAL_TYPES
#:set IR_KINDS = INTEGER_KINDS + REAL_KINDS
#:set IR_KINDS_TYPES = list(zip(IR_KINDS, IR_TYPES))
#:endmute
#:set HISTORY_FLAGS = [False, True]
